{
    "title" : " KeyError ",
    "text": " *원인* : 딕셔너리에서 `존재하지 않는 키에 접근` 하는 경우 발생합니다. \n *해결방안* : 딕셔너리의 키를 확인 후 사용하세요. 참고로, 딕셔너리의 키를 확인하는 방법은 `dict_name.keys()` 입니다. \n",
    "mrkdwn": true
}